### ISSUE TITLE
Asterinas exits quietly when panic

### ISSUE THREAD

**Issue by Marsman1996** [asterinas/asterinas#1477]
### Your Question

Asterinas exits quietly when a panic is triggered, is it a new feature? 🤔

### What You Have Tried

For example, if we run `ping www.baidu.com`, because of the `todo!` in 
https://github.com/asterinas/asterinas/blob/998869d57e0e35929348d41f7be19aab866c1f02/kernel/src/util/net/options/mod.rs#L130-L137
A panic is triggered and Asterinas exited with some error info such as stack info. 
However, now Asterinas exits quietly (master 998869d)
![image](https://github.com/user-attachments/assets/d49e62ee-fdda-41ed-a6d7-19553cf58016)

**Comment by junyang-zh** [comment]
It's because of a bad implementation in #1379 , which unconditionally call `begin_panic` without being enclosed in `catch_unwind` in the panic handler. Now with the fix of #1478 the entire thread is aware of whether this thread should catch panics, so `begin_panic` won't happen if `catch_unwind` is absent.
