### ISSUE TITLE
Improve the support of tcp backlog

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#457]
Smoltcp does not support backlog for tcp listen, so we have created `backlog` sockets listening on the same port to mimic the linux behavior.

However, suppose `backlog` connections come from client and abort,  the server does not accept any connection meanwhile. If the client sends a new connection request, the server cannot response to the connection request. For linux, the server can continue responsing again.

The possible solution is to have a backgroud thread to make any socket listen again if it is closed before accepting. But this will surely affect performance.

**Comment by lrh2000** [comment]
> However, suppose `backlog` connections come from client and abort, the server does not accept any connection meanwhile. If the client sends a new connection request, the server cannot response to the connection request. For linux, the server can continue responsing again.

What exactly is the point of this paragraph?

For connections in the SYN queue (where connections have not yet been established), [smoltcp will reset their socket states to `State::LISTEN` when they're reset](https://github.com/smoltcp-rs/smoltcp/blob/cc241fa7bd68cc181b422b819eac10227d32f70e/src/socket/tcp.rs#L1734-L1743), so that they can continue to listen for new connections. I don't think this is a problem.

For connections in the accept queue (where connections have already been established), they will still be acceptable even if they're reset.
```
> python
Python 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> import socket
>>> s = socket.socket()
>>> s.listen()
>>> s
<socket.socket fd=3, family=2, type=1, proto=0, laddr=('0.0.0.0', 48779)>
>>> t = socket.socket()
>>> t.connect(('127.0.0.1',48779))
>>> t.setsockopt(socket.SOL_SOCKET, socket.SO_LINGER, struct.pack('ii', 1, 0))
>>> t.close()
>>> x = s.accept()
>>> x[0].send(b'')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ConnectionResetError: [Errno 104] Connection reset by peer
```

So in terms of this issue and the backlog implementation, I don't think there's anything to fix. Our current implementation is correct, and we'll still be correct after the new backlog optimization.

I would like to have regression tests for the above behavior, but it is not currently actionable because we don't support `SO_LINGER`, so we have no way to manually trigger the connection reset. We may add some regression tests in the future.

**Comment by lrh2000** [comment]
> For connections in the accept queue (where connections have already been established), they will still be acceptable even if they're reset.

Oh, we currently use `may_send` to decide if a connection can be accepted, which rejects connections that were established but have now been reset.
https://github.com/asterinas/asterinas/blob/18d5eb1f02825ce80cefc8a9c09e6931a0c2ac9e/kernel/src/net/socket/ip/stream/listen.rs#L157-L159

That should be what this issue means, right? If so, #1690 should fix it.

**Comment by StevenJiang1110** [comment]
> Oh, we currently use `may_send` to decide if a connection can be accepted, which rejects connections that were established but have now been reset.

Yes, I believe that's the case. We haven't handled backlog sockets in the `Close` state before. These sockets can be established sockets that have been reset by the remote peer. 

Such scenarios are covered by the gVisor socket test suite, which is quite extensive. I identified the issue while attempting to enable the gVisor socket test suite. However, since the gVisor test cases bind/listen/connect to `0.0.0.0`, which we haven't supported yet, these tests have not been incorporated into our CI process.

**Comment by lrh2000** [comment]
Good to know. Thanks for the clarification!
