### ISSUE TITLE
Clean_for_close should not be called when calling syscall close

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#506]
Related to #494.

### Introduction
When we calling syscall `close` to remove a fd from file table, the syscall will also try to do some cleanup task such as flushing the data to disk, or sending `FIN` and waiting for `FIN-ACK`.

```rust
let mut file_table = current.file_table().lock();
let file = file_table.close_file(fd).unwrap();
file.clean_for_close()?;
```

However, there are two main problems, 
1. If multiple fds point to the same file (Multiple fds may be shared between child and parent process during fork), only closing the last fd should call `clean_for_close`. The current code will call `clean_for_close` everytime we close a fd.
2. `clean_for_close` is a time-consuming task, it should not blocking the thread since close syscall should return immedaitely.

### Possible Solution
The suitable place to do cleanup for structs who implement `FileLike` may be the `drop` method. The drop method will only be called when last file is removed, which solves problem 1.

To deal with problem 2, we do not do real cleanup work in drop method, but just submit a `WorkItem`.

### Drawback
When creating a `WorkItem`, we may want to pass the ownership of file/socket to `WorkItem`. However, even we hold `Weak<Self>` in file/socket, we cannot upgrade to `Arc<Self>` in drop method. We may only construct a new struct with file/socket's fields and pass the new struct to `WorkItem`.

### Unsolved questions
- The solution is enough for socket, what about files?
- The socket linger option may requires that the cleanup code runs in current thread. Then we need to do time-consuming job in `drop` method. Is it acceptable?

**Comment by tatetian** [comment]
I agree that the design of `clean_for_close` deserves some scrutiny. But it seems to me that the current proposal is designed with sockets in mind. Could you make a list about the (potential) users of `clean_for_close`? Try name three for the sake of generalization. We need to have a good understanding of these users to make good design decisions.

> `clean_for_close` is a time-consuming task, it should not blocking the thread since close syscall should return immedaitely.

Currently, the only useful thing done in `clean_for_close` is to sync a file. I don't know how Linux implements it. But a safer strategy is to finish file sync before returning the `close` system call to the user. So I am convinced about the conclusion that the "close syscall should return immediately".

> The suitable place to do cleanup for structs who implement FileLike may be the drop method.

As I said earlier, I am not convinced that we can rule out the possibilities that, for certain files, the cleanup-before-close job should be done _upon_ close (rather than _after) close). In this case, doing time-consuming operations in `drop` synchronously is not suitable.

With the concerns above, I am wondering if the following design.

```rust
/// An open file.
///
/// All open files of a process are kept in the file table.
pub struct OpenFile(Arc<dyn FileLike>);

impl OpenFile {
    /// Closes an open file.
    ///
    /// If this is the last instance of `OpenFile` refers to the underlying file object,
    /// then this method triggers the clean up logic specific to the file type.
    pub fn close(mut self) {
        if Arc::strong_count(&self) > 1 {
            return;
        }

        // Avoid triggering Fd::drop
        let Self { file } = self;

        self.0.close_last_ref(&file);
    }
}

impl Drop for Fd {
    fn drop(&mut self) {
        panic!("Call Fd::close instead")
    }
}

impl FileLike {
    /// Close the last instance of `Arc` that refers to `self`.
    ///
    /// This method allows for file type-specific cleanup logic to be triggered
    /// before the last reference to file is dropped.
    ///
    /// The caller should ensure 
    /// 1. `last` refers to `self`;
    /// 2. `Arc::strong_cnt(last) == 1`;
    /// 3. After calling this method, both `self` and `last` will not be used by the caller.
    ///
    /// For efficiency, an implementation may decide to do clean-up in an asynchronous manner.
    /// To do so, this method may may capture the ownership of the file by cloning `last`.
    /// In other words, although the caller is not allowed to use the file any more,
    /// it does not prevent the file from being used for the clean-up purpose of this method
    /// _after_ the method returns.
    fn close_last_ref(&self, last: &Arc<dyn FileLike>);
}
```

**Comment by StevenJiang1110** [comment]
I stuides the implementation of [the close syscall](https://elixir.bootlin.com/linux/v6.10/source/fs/open.c#L1548) in Linux and engaged in some offline discussions with @lucassong-mh.

```C
SYSCALL_DEFINE1(close, unsigned int, fd)
{
    int retval;
    struct file *file;

    // Remove file from file table and get the file structure
    file = file_close_fd(fd);
    if (!file)
        return -EBADF;

    // Flush
    retval = filp_flush(file, current->files);

    // Fput
    __fput_sync(file);

    // Check errors.......
    
    return retval;
}
```

After removing the file descriptor from the file table, there are two operations that follow: `flush` and `fput`.

The `flush` operation is invoked every time a fd is closed (similar to our current `clean-for-close` method). This operation subsequently calls the `file_operations.flush` function defined within each subsystem. In most cases, such as [ext2](https://elixir.bootlin.com/linux/v6.10/source/fs/ext2/file.c#L311), [ext4](https://elixir.bootlin.com/linux/v6.10/source/fs/ext4/file.c#L929),  [socket](https://elixir.bootlin.com/linux/v6.10/source/net/socket.c#L154), the `flush` function is essentially a _no-op_. However, certain filesystems like [nfs](https://elixir.bootlin.com/linux/v6.10/source/fs/nfs/file.c#L893) do implement the `flush` method, though its exact implications are not entirely clear to me.

The `fput` function, on the other hand, is a [no-op](https://elixir.bootlin.com/linux/v6.10/source/fs/file_table.c#L506) if the reference count of the file is not zero. Once the reference count drops to zero, it ultimately calls [file_operations.release](https://elixir.bootlin.com/linux/v6.10/source/fs/file_table.c#L421). For filesystems like [ext2](https://elixir.bootlin.com/linux/v6.10/source/fs/ext2/file.c#L143) and [ext4](https://elixir.bootlin.com/linux/v6.10/source/fs/ext4/file.c#L166), this release function eventually handles discard reservation/preallocation on the inode, which is currently a no-op for our implementation. In the context of TCP sockets, the `release` function will finally call [tcp_close](https://elixir.bootlin.com/linux/v6.10/source/net/ipv4/tcp.c#L2785) to send a FIN packet. If the linger socket option is set, `tcp_close` will wait for the socket to receive the responce packet.

In summary, `FileLike::clean_for_close` corresponds to `file_operations.flush` in the Linux kernel and is called each time a fd is closed. This method is a _no-op_ for ext2, ext4, and network subsystems in linux kernel but may have utility for future use cases like NFS. Removing this method like #1092 is acceptable for me. Even the method is not removed, I recommend renaming it for clearness.

The `file_operations.release` function is not covered by our current implementation. This function is invoked when the reference count decreases to zero and can block for a significant amount of time, making it unsuitable for calls within the `drop` method. The design mentioned in the [earlier comment](https://github.com/asterinas/asterinas/issues/506#issuecomment-2246808814) appears to be better solution.

**Comment by lrh2000** [comment]
> As I said earlier, I am not convinced that we can rule out the possibilities that, for certain files, the cleanup-before-close job should be done upon close (rather than _after) close).

This is incorrect. Please also read the "Multithreaded processes and close()" section in the [manual page](https://man7.org/linux/man-pages/man2/close.2.html).

>> On Linux (and possibly some other systems), the behavior is
       different: the blocking I/O system call holds a reference to the
       underlying open file description, and this reference keeps the
       description open until the I/O system call completes.  (See
       [open(2)](https://man7.org/linux/man-pages/man2/open.2.html) for a discussion of open file descriptions.)  Thus, the
       blocking system call in the first thread may successfully
       complete after the close() in the second thread.

So I'm afraid the design of `close_last_ref` doesn't make sense. We don't need to look at the Linux implementation. A look at the manual page will reveal the conclusion.

> In this case, doing time-consuming operations in drop synchronously is not suitable.

Linux [uses `task_work_add` to avoid time-consuming operations in `fput`](https://elixir.bootlin.com/linux/v6.10/source/fs/file_table.c#L481). We can do the similar thing in the future.

**Comment by lrh2000** [comment]
> In summary, `FileLike::clean_for_close` corresponds to `file_operations.flush` in the Linux kernel and is called each time a fd is closed.

I'm curious why we don't call `FileLike::flush` directly in `sys_close`? It looks more consistent with the Linux implementation.

**Comment by lrh2000** [comment]
> ```rust
>     /// Closes an open file.
>     ///
>     /// If this is the last instance of `OpenFile` refers to the underlying file object,
>     /// then this method triggers the clean up logic specific to the file type.
>     pub fn close(mut self) {
>         if Arc::strong_count(&self) > 1 {
>             return;
>         }
> 
>         // Avoid triggering Fd::drop
>         let Self { file } = self;
> 
>         self.0.close_last_ref(&file);
>     }
> ```

I even considered this before opening #1092. But on second thought, I realize that the problem with this solution is how we handle the case where the two processes concurrently close two file descriptors pointing to the same underlying `FileLike`? This leads to exactly the same thing as described in https://github.com/asterinas/asterinas/issues/671, so the `FileLike` structure will be leaked.

**Comment by StevenJiang1110** [comment]
> I'm curious why we don't call FileLike::flush directly in sys_close? It looks more consistent with the Linux implementation.

I don't know the original reason why we introduced `clean_for_close`. This method has actually not been used for a long time. However, directly using `FileLike::flush` is better than the current form.

But flush is still a confusing name. It is surprising to me that most filesystems implement flush as a _no-op_. Even for filesystems that implement flush, it is not easy to tell the difference between `flush` and `fsync`. Since `flush` is only used in the kernel and is not exposed to users via syscalls, I think we should give it a clearer name if we do need this method.

**Comment by lrh2000** [comment]
> But flush is still a confusing name. It is surprising to me that most filesystems(ext2, ext4, xfs, btrfs, etc) implement `file_operations.flush` as a _no-op_. Even for filesystems that implement flush(like nfs), it is not easy to tell the difference between `file_operations.flush` and `file_operations.fsync`. Since `flush` is only used in the kernel and is not exposed to users via syscalls, I think we should give it a clearer name if we do need this method.

This makes sense.

It seems that `flush` is only called before closing file descriptors, so `flush` is essentially `clean_for_close`, but this also implies that we _don't_ need _both_ `flush` and `clean_for_close`, at least one has to be removed.

But note that there are always races between `flush` (or `clean_for_close`) and `fput` (or dropping `FileLike`), so the semantics of this function are indeed in a mess.

I think the purpose of `flush`/`clean_for_close` is just to provide error codes for `close()` for diagnostic purposes (since `fput`/dropping `FileLike` can never return a value), as documented in the "Dealing with error returns from close()" section of the [manual pages](https://man7.org/linux/man-pages/man2/close.2.html):
>>A careful programmer will check the return value of close(),
       since it is quite possible that errors on a previous [write(2)](https://man7.org/linux/man-pages/man2/write.2.html)
       operation are reported only on the final close() that releases
       the open file description.  Failing to check the return value
       when closing a file may lead to silent loss of data.  This can
       especially be observed with NFS and with disk quota.
>>
>>Note, however, that a failure return should be used only for
       diagnostic purposes (i.e., a warning to the application that
       there may still be I/O pending or there may have been failed I/O)
       or remedial purposes (e.g., writing the file once more or
       creating a backup).

and also the "ERRORS" section:
>> ENOSPC/EDQUOT
On NFS, these errors are not normally reported against the
              first write which exceeds the available storage space, but
              instead against a subsequent [write(2)](https://man7.org/linux/man-pages/man2/write.2.html), [fsync(2)](https://man7.org/linux/man-pages/man2/fsync.2.html), or
              close().


So my suggestion is to either
 - find a better name for `flush`/`clean_for_close`, perhaps something like `on_each_close`, which emphasizes that it is acceptable to call this method on any file descriptor that is close to the same underlying `FileLike` structure, or
 - remove both `flush` and `clean_for_close` completely _for now_, because I don't see that such a method can make a difference for any filesystems we're going to implement in the near future, and when we are ready to implement NFS, which actually needs this method, that will be the right time to rethink the behavior.

**Comment by tatetian** [comment]
@StevenJiang1110 Good job on digging into Linux's behaviors. I withdraw my proposal and vote for the second option proposed by @lrh2000, which is to "remove both flush and clean_for_close completely for now".

**Comment by lrh2000** [comment]
>  vote for the second option proposed by @lrh2000, which is to "remove both flush and clean_for_close completely for now".

Good to know. I also have a slight preference for the second option, in the spirit of avoiding code without implementors and making our codebase cleaner. We can always reconsider the behavior after it becomes necessary.

Done in https://github.com/asterinas/asterinas/pull/1092. But I think this issue can be kept open until the behavior of closing sockets is fixed. I'll open another PR for this.

**Comment by lrh2000** [comment]
Perhaps interestingly, I found that we're actually able to write this:
```rust
use std::sync::Arc;

pub trait F {
    fn dropping(self: Arc<Self>);
}

struct S;

impl F for S {
    fn dropping(self: Arc<Self>) {
        let Some(_inner) = Arc::into_inner(self) else {
            return;
        };
        
        // Do something with `inner`
    }
}

pub fn dropping(f: Arc<dyn F>) {
    f.dropping();
}
```

In other words, `fn dropping(self: Arc<Self>)` is object-safe (but note that `fn foo(self: &Arc<Self>)` is not). So we can use `Arc::into_inner` to catch the last reference, which fixes the race condition described in https://github.com/asterinas/asterinas/issues/506#issuecomment-2247550382.

This is just a note. The special syntax may be useful in other scenarios. I still don't think we should switch to the proposal described in https://github.com/asterinas/asterinas/issues/506#issuecomment-2246808814 because of https://github.com/asterinas/asterinas/issues/506#issuecomment-2247352953 and https://github.com/asterinas/asterinas/issues/506#issuecomment-2247420407.

**Comment by StevenJiang1110** [comment]
> Perhaps interestingly, I found that we're actually able to write this ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ca4c558dacda0ab93e17e001925dc167)):

Do you want to get `self` instead of `&mut self` in `drop` method by this design?

If so, how do you like the [ScopeGuard](https://rust-for-linux.github.io/docs/kernel/struct.ScopeGuard.html) introduced by Rust for Linux? The `ScopeGuard` allows setting cleanup functions which accepts `self`.

I thought this may be useful for some scenarios but I do not find a motivating example yet.

**Comment by lrh2000** [comment]
> Do you want to get `self` instead of `&mut self` in `drop` method by this design?

In fact, I just want to know if there is a way to fix the race condition in @tatetian's suggestion.

> If so, how do you like the [ScopeGuard](https://rust-for-linux.github.io/docs/kernel/struct.ScopeGuard.html) introduced by Rust for Linux? The `ScopeGuard` allows setting cleanup functions which accepts `self`.
> 
> I thought this may be useful for some scenarios but I do not find a motivating example yet.

Actually, I think its main purpose is not to make the drop function accept `self` (which can always be done via `Option` or `Takeable`). It is to make the cleanup function run even if the function is terminated early by, say, `?` desugar.

I think in many places in our code base, we have already mistakenly assumed that using `?` desugar properly cleans everything for us. For example, in the `pipe2` system call, we previously forgot to close the pipe files when errors occur while writing the file descriptors back to userspace. This has been fixed by https://github.com/asterinas/asterinas/commit/8df51ab0010.
