### ISSUE TITLE
[Performance] `memset` is too slow

### ISSUE THREAD

**Issue by skpupil** [asterinas/asterinas#763]
While testing the 401.bzip benchmark of SPEC CPU 2006, I noticed that the Asterinas kernel performs very slowly when handling user malloc and memset. The following program takes nearly 20 seconds to run on Asterinas, whereas it takes less than 0.01 seconds on Linux. 

 By the way, the design of using vmar mapping to vmo and vmo utilizing a tree-like structure for querying is overly complex and performs poorly without apparent benefits. I believe it's time to consider simplifying the design and eliminating the vmo, which is a peculiar artifact from the microkernel. 
I'd like to understand the advantages, if any, of the intricate design of vmo. Please tell me. Thanks.
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define TOTAL_MEMORY_SIZE 200 * 1024 * 1024 // 100MB

int main() {
    int num_allocations = 5;
    int each_allocation_size = TOTAL_MEMORY_SIZE / num_allocations;

    char *memory_block = NULL;

    for (int i = 0; i < num_allocations; i++) {
        memory_block = (char *)malloc(each_allocation_size);
        if (memory_block == NULL) {
            printf("malloc fail\n");
            exit(1);
        }

        memset(memory_block, 0, each_allocation_size);

    }

    free(memory_block);

    return 0;
}

```

**Comment by skpupil** [comment]
![image](https://github.com/asterinas/asterinas/assets/56211074/acaeac47-fbc0-4ebe-be8f-a404899e0ac8)

**Comment by cchanging** [comment]
> The following program takes nearly 20 seconds to run on Asterinas

Thanks for your issues. The reason for the slow execution of this program is due to the handling of page faults caused by `memset` (current `mmap` performance is on par with Linux in terms of efficiency). Currently, Asterinas is handling page faults page by page, indeed there are still bottlenecks in efficiency which we plan to continuously optimize. 

The removal of `Vmo` usage in `Vmar`, as you mentioned, is exactly what we are aiming to do. This improvement would significantly reduce the complexity of the VM module’s code. The redesign is currently in the planning stages, and we expect to soon present the relevant design documentation. We welcome your continued valuable suggestions and insights.

**Comment by skpupil** [comment]
@cchanging I retested the program using the time command, and it took approximately 0.8 seconds. The optimization improvement is significant, and I believe this level of performance is completely acceptable. Thx.
