### ISSUE TITLE
The CI `osdk-doc-env-test` randomly hangs

### ISSUE THREAD

**Issue by lrh2000** [asterinas/asterinas#779]
The CI `osdk-doc-env-test` can finish within 5 minutes in most runs:
https://github.com/asterinas/asterinas/actions/runs/8781560534/job/24093827863

However, it cannot finish after 15 minutes in some CI runs:
https://github.com/asterinas/asterinas/actions/runs/8781176026/job/24092629664
https://github.com/asterinas/asterinas/actions/runs/8585860702/job/23527706471

Notably, it always hangs after printing (see the above two examples):
```
test integration::build_with_conditional_manifest ... ok
````
I don't think we can solve the problem by simply extending the CI timeout. There should be some bugs we need to find out and fix.

**Comment by tatetian** [comment]
@lrh2000 Thanks for filing this bug.

@StevenJiang1110  Could you dig into this bug?

**Comment by StevenJiang1110** [comment]
It seems some test case hangs due to some reasons.

For [the first ci failure](https://github.com/asterinas/asterinas/actions/runs/8781176026/job/24092629664), `create_and_run_kernel` case does not exit as expected.

<img width="1159" alt="截屏2024-04-23 14 27 58" src="https://github.com/asterinas/asterinas/assets/27764680/6dca97e7-718b-46e1-a691-df5788c70998">


For [the second ci failure](https://github.com/asterinas/asterinas/actions/runs/8585860702/job/23527706471), `work_in_workspace` hangs.

<img width="1242" alt="截屏2024-04-23 14 30 04" src="https://github.com/asterinas/asterinas/assets/27764680/f2d8d65a-7993-4663-a6b5-c9ca232b7ec9">

I will look at the actual reason why some cases hang up.

**Comment by lrh2000** [comment]
I don't see this problem for a long time, closing as outdated. Please reopen if necessary.
