### ISSUE TITLE
[BUG] Kernel boot fails when using large physical memory.

### ISSUE THREAD

**Issue by Hsy-Intel** [asterinas/asterinas#907]
Kernel can't boot with the physical memory larger than 128G.

Reproduce method:

Set QEMU args in `tools/qemu_args.sh`:

```rust
-m ${MEM:-128G}
```

**Comment by junyang-zh** [comment]
The root cause is that when allocating frames, the frame allocator would give you frames > 4G when using 128G physical memory. The frame metadata pages are allocated in the phase that > 4G mappings are not built, and we need many metadata pages when using 128G physical memory, which would ensure our failure.

I am considering refactoring the frame allocator to avoid this.
